import{S as g,i as a,a as p}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=i(r);fetch(r.href,s)}})();const h=new g(".gallery a",{captionsData:"alt",captionDelay:250});function d(t){const e=document.querySelector(".gallery"),i=t.map(o=>`
    <div class="image-card">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="img-details">
     <div class="coms"> <p>Likes</p> ${o.likes}</div>
      <div class="coms"><p>Views</p> ${o.views}</div>
      <div class="coms"><p>Comments</p> ${o.comments}</div>
      <div class="coms"><p>Downloads</p> ${o.downloads}</div>
      </div>
      </div>
    `).join("");e.insertAdjacentHTML("beforeend",i),h.refresh()}function v(t){a.error({title:"Error",message:t.message,position:"topRight",timeout:5e3})}function m(t){const e=document.getElementById("loader");t?e.style.display="block":e.style.display="none"}n(!1);function n(t){const e=document.querySelector(".load-more");t?e.style.display="block":e.style.display="none"}const b="46931303-4adba5c677ceeed1d52c819f0",w="https://pixabay.com/api/",f={image_type:"photo",orientation:"horizontal",safesearch:!0};let u=1;async function y(t,e=1,i=20,o=f){m(!0);try{const r=`${w}?key=${b}&q=${encodeURIComponent(t)}&page=${e}&per_page=${i}&image_type=${o.image_type}&orientation=${o.orientation}&safesearch=${o.safesearch}`,s=await p.get(r);if(s.status!==200)throw new Error("Error fetching images");return s.data.hits}catch(r){throw console.error(r),r}finally{n(!0)}}const L=document.querySelector(".load-more");L.addEventListener("click",async()=>{const t=document.querySelector('#form input[name="query"]').value.trim();if(t){u+=1,n(!1);try{const e=await y(t,u,15,f);e.length===0?(a.info({title:"We are sorry,",message:"but you have reached the end of search results.",position:"topRight",timeout:3e3}),n(!1)):(d(e),$(),n(!0))}catch(e){throw console.error(e),e}finally{m(!1)}}});function $(){const t=document.querySelector(".image-card");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}}function l(t){const e=document.getElementById("loader");t?e.style.display="block":e.style.display="none"}const q=document.querySelector("#form");q.addEventListener("submit",async t=>{t.preventDefault();const e=t.target.elements.query.value.trim();if(document.querySelector(".gallery").innerHTML="",!e){l(!1),a.error({title:"Sorry,",message:"there are no images matching your search query. Please, try again!",position:"topRight",timeout:3e3});return}l(!0);try{const i=await y(e);i.length===0?a.error({title:"Sorry,",message:"There are no images matching your search query. Please, try again!",position:"topRight",timeout:3e3}):d(i)}catch(i){v(i)}finally{l(!1)}});
//# sourceMappingURL=index.js.map
